//! End-to-end: extract, link and check the synthetic `acme-goods` workspace
//! generated by knowell-eval (seed 42, small), entirely in memory.
//!
//! Asserts that
//! - the linker connects the web and mobile `cancelSubscription` calls to the
//!   billing endpoint, the billing publisher to both consumers of
//!   `subscription.cancelled`, the ledger publisher to both consumers of
//!   `payment.captured`, orders-service to the ledger RPC defined in proto,
//!   and keeps dynamic keys as unresolved placeholders;
//! - `check` reports the planted issues and nothing else beyond the
//!   documented allow-list below (true observations about the fixture) and
//!   findings located only in generated noise files;
//! - no secret value from the fixture ever appears in any output, and the
//!   committed `.env` file is never read.

#![allow(
    clippy::unwrap_used,
    clippy::expect_used,
    clippy::panic,
    clippy::indexing_slicing,
    clippy::print_stdout
)]

use std::collections::{BTreeMap, BTreeSet};
use std::sync::OnceLock;

use knowell_core::{Name, RepoPath};
use knowell_eval::{FileRole, Fixture, FixtureSpec, Scale, generate, planted_issues};
use knowell_graph::{
    ATTR_SCHEMA_HASH, ContractKind, Edge, EdgeKind, EvidenceType, FlowDirection, FlowSpec, NodeId,
    Resolution,
};
use knowell_link::{
    CHECK_RULES, CheckOptions, ExtractOptions, FINGERPRINT_KEY, Finding, LinkOptions, LinkOutput,
    PackSet, ProjectExtractions, check, extract_project, link, to_sarif,
};

struct Run {
    fixture: Fixture,
    projects: Vec<ProjectExtractions>,
    linked: LinkOutput,
    findings: Vec<Finding>,
    /// Paths the extractor asked to read, per project.
    read: BTreeMap<String, BTreeSet<String>>,
}

fn execute() -> Run {
    let fixture = generate(&FixtureSpec {
        seed: 42,
        scale: Scale::Small,
    });
    let packs = PackSet::builtin().unwrap();
    let mut projects = Vec::new();
    let mut read: BTreeMap<String, BTreeSet<String>> = BTreeMap::new();
    for project in fixture.projects() {
        let contents: BTreeMap<&RepoPath, &str> = project
            .files
            .iter()
            .map(|f| (&f.path, f.content.as_str()))
            .collect();
        let paths: Vec<RepoPath> = project.files.iter().map(|f| f.path.clone()).collect();
        let seen = read.entry(project.name.to_string()).or_default();
        projects.push(extract_project(
            &project.name,
            &paths,
            &packs,
            &ExtractOptions::default(),
            &mut |path| {
                seen.insert(path.to_string());
                contents.get(path).map(|s| (*s).to_owned())
            },
        ));
    }
    let linked = link(&projects, &LinkOptions::default()).unwrap();
    let findings = check(&projects, &linked, &CheckOptions::default()).unwrap();
    Run {
        fixture,
        projects,
        linked,
        findings,
        read,
    }
}

fn run() -> &'static Run {
    static RUN: OnceLock<Run> = OnceLock::new();
    RUN.get_or_init(execute)
}

fn sarif(run: &Run, version: &str) -> serde_json::Value {
    let roots = run
        .projects
        .iter()
        .map(|project| {
            (
                project.project.clone(),
                url::Url::parse(&format!("file:///fixture/{}/", project.project)).unwrap(),
            )
        })
        .collect();
    to_sarif(&run.findings, version, &roots).unwrap()
}

fn name(project: &str) -> Name {
    Name::new(project).unwrap()
}

fn symbol(project: &str, key: &str) -> NodeId {
    NodeId::symbol(&name(project), key)
}

fn edge<'a>(linked: &'a LinkOutput, from: &NodeId, to: &NodeId, kind: EdgeKind) -> &'a Edge {
    linked
        .edges()
        .values()
        .flat_map(|edges| edges.values())
        .find(|r| &r.from == from && &r.to == to && r.edge.kind == kind)
        .map(|r| &r.edge)
        .unwrap_or_else(|| panic!("missing edge {from} -{}-> {to}", kind.as_str()))
}

fn is_core(fixture: &Fixture, project: &str, path: &str) -> bool {
    fixture
        .file(&format!("{project}/{path}"))
        .is_some_and(|f| f.role == FileRole::Core)
}

#[test]
fn links_web_and_mobile_cancellation_to_the_billing_endpoint() {
    let run = run();
    let endpoint = NodeId::contract(ContractKind::Endpoint, "POST /v1/subscriptions/{}/cancel");
    let web = symbol(
        "storefront-web",
        "src/api/subscriptions.ts#cancelSubscription",
    );
    let mobile = symbol(
        "mobile-app",
        "lib/api/subscription_api.dart#SubscriptionApi.cancelSubscription",
    );
    let controller = symbol(
        "billing-api",
        "src/subscriptions/subscriptions.controller.ts#SubscriptionsController.cancel",
    );
    for client in [&web, &mobile] {
        let e = edge(&run.linked, client, &endpoint, EdgeKind::Consumes);
        // Client paths interpolate the id at run time: matched heuristically.
        assert_eq!(e.evidence, EvidenceType::Heuristic, "{client}");
        assert_eq!(e.resolution, Resolution::Resolved, "{client}");
    }
    let served = edge(&run.linked, &controller, &endpoint, EdgeKind::Exposes);
    // The route is documented in contracts/openapi/billing-api.yaml.
    assert_eq!(served.evidence, EvidenceType::ContractDerived);
    let openapi = NodeId::file(
        &name("contracts"),
        &RepoPath::new("openapi/billing-api.yaml").unwrap(),
    );
    edge(&run.linked, &openapi, &endpoint, EdgeKind::Defines);

    let graph = run.linked.graph().unwrap();
    for client in [web, mobile] {
        let trace = graph
            .trace_flow(&FlowSpec::between(client.clone(), controller.clone()))
            .unwrap();
        let best = trace
            .paths
            .first()
            .unwrap_or_else(|| panic!("no flow from {client}"));
        assert_eq!(best.contracts, vec![endpoint.clone()]);
        assert_eq!(best.projects.last(), Some(&name("billing-api")));
        assert_eq!(best.flagged_hops, 0);
    }
    // The undocumented resume route is still linked, but only syntactically.
    let resume = NodeId::contract(ContractKind::Endpoint, "POST /v1/subscriptions/{}/resume");
    let resume_controller = symbol(
        "billing-api",
        "src/subscriptions/subscriptions.controller.ts#SubscriptionsController.resume",
    );
    assert_eq!(
        edge(&run.linked, &resume_controller, &resume, EdgeKind::Exposes).evidence,
        EvidenceType::Syntactic
    );
    edge(
        &run.linked,
        &symbol(
            "storefront-web",
            "src/api/subscriptions.ts#resumeSubscription",
        ),
        &resume,
        EdgeKind::Consumes,
    );
}

#[test]
fn links_events_rpcs_and_service_calls_across_projects() {
    let run = run();
    let cancelled = NodeId::contract(ContractKind::Topic, "subscription.cancelled");
    let publisher = symbol(
        "billing-api",
        "src/subscriptions/subscription.service.ts#SubscriptionService.cancelSubscription",
    );
    let worker = symbol("notification-worker", "src/consumer.rs#run");
    let orders = symbol(
        "orders-service",
        "internal/events/subscription_consumer.go#NewSubscriptionCancelledConsumer",
    );
    edge(&run.linked, &publisher, &cancelled, EdgeKind::Produces);
    let worker_edge = edge(&run.linked, &worker, &cancelled, EdgeKind::Consumes);
    // `consumer.subscribe(TOPICS)` resolved through a constant, and the
    // topic is defined by contracts/events/subscription.cancelled.v1.json.
    assert_eq!(worker_edge.evidence, EvidenceType::ContractDerived);
    assert_eq!(worker_edge.resolution, Resolution::Resolved);
    edge(&run.linked, &orders, &cancelled, EdgeKind::Consumes);
    let graph = run.linked.graph().unwrap();
    let flows = graph
        .trace_flow(
            &FlowSpec::open(publisher.clone(), FlowDirection::Downstream).with_max_paths(20),
        )
        .unwrap();
    let reached: BTreeSet<&NodeId> = flows.paths.iter().flat_map(|p| p.nodes.iter()).collect();
    assert!(reached.contains(&worker), "{reached:?}");
    assert!(reached.contains(&orders), "{reached:?}");

    let captured = NodeId::contract(ContractKind::Topic, "payment.captured");
    edge(
        &run.linked,
        &symbol(
            "ledger-service",
            "ledger/events.py#EventPublisher.payment_captured",
        ),
        &captured,
        EdgeKind::Produces,
    );
    edge(&run.linked, &worker, &captured, EdgeKind::Consumes);
    edge(
        &run.linked,
        &symbol(
            "orders-service",
            "internal/events/payment_consumer.go#NewPaymentCapturedConsumer",
        ),
        &captured,
        EdgeKind::Consumes,
    );

    let rpc = NodeId::contract(
        ContractKind::Rpc,
        "acme.ledger.v1.LedgerService/GetPaymentStatus",
    );
    let client = edge(
        &run.linked,
        &symbol(
            "orders-service",
            "internal/ledger/client.go#Client.PaymentStatus",
        ),
        &rpc,
        EdgeKind::Consumes,
    );
    assert_eq!(client.evidence, EvidenceType::Heuristic);
    edge(
        &run.linked,
        &symbol(
            "ledger-service",
            "ledger/grpc_server.py#LedgerServicer.GetPaymentStatus",
        ),
        &rpc,
        EdgeKind::Exposes,
    );
    let proto = NodeId::file(
        &name("contracts"),
        &RepoPath::new("proto/ledger/v1/ledger.proto").unwrap(),
    );
    edge(&run.linked, &proto, &rpc, EdgeKind::Defines);

    edge(
        &run.linked,
        &symbol(
            "billing-api",
            "src/orders/orders.client.ts#OrdersClient.createOrder",
        ),
        &NodeId::contract(ContractKind::Endpoint, "POST /v1/orders"),
        EdgeKind::Consumes,
    );
    edge(
        &run.linked,
        &symbol(
            "billing-api",
            "src/payments/ledger.client.ts#LedgerClient.capture",
        ),
        &NodeId::contract(ContractKind::Endpoint, "POST /v1/payments/capture"),
        EdgeKind::Consumes,
    );
    // The orders history is fetched with a dynamic query suffix
    // (`/v1/orders${query}`) and still links, heuristically.
    let history = edge(
        &run.linked,
        &symbol("storefront-web", "src/api/orders.ts#listOrders"),
        &NodeId::contract(ContractKind::Endpoint, "GET /v1/orders"),
        EdgeKind::Consumes,
    );
    assert_eq!(history.evidence, EvidenceType::Heuristic);
}

#[test]
fn tables_env_names_i18n_and_unresolved_uses() {
    let run = run();
    let subscriptions = NodeId::contract(ContractKind::Table, "subscriptions");
    let graph = run.linked.graph().unwrap();
    let current = graph
        .node(&subscriptions)
        .and_then(|n| n.attr(ATTR_SCHEMA_HASH))
        .unwrap()
        .to_owned();
    let billing = edge(
        &run.linked,
        &symbol(
            "billing-api",
            "src/subscriptions/subscription.entity.ts#SubscriptionEntity",
        ),
        &subscriptions,
        EdgeKind::Reads,
    );
    assert_eq!(billing.attr(ATTR_SCHEMA_HASH), Some(current.as_str()));
    let ledger = edge(
        &run.linked,
        &symbol("ledger-service", "ledger/db/models.py#SubscriptionRow"),
        &subscriptions,
        EdgeKind::Reads,
    );
    let older = ledger.attr(ATTR_SCHEMA_HASH).unwrap();
    assert_ne!(older, current);
    // The ledger read model matches the table as of migration 0008.
    let schema = run.linked.tables().get("subscriptions").unwrap();
    let version = schema.versions.iter().find(|v| v.hash == older).unwrap();
    assert!(
        version
            .path
            .as_str()
            .ends_with("0008_add_cancelled_at_to_subscriptions.sql")
    );

    // Env names: code reads link to deployment declarations by name.
    let smtp = NodeId::contract(ContractKind::EnvName, "SMTP_PASSWORD");
    edge(
        &run.linked,
        &symbol("notification-worker", "src/config.rs#Config.from_env"),
        &smtp,
        EdgeKind::Reads,
    );
    let compose = NodeId::file(
        &name("infra"),
        &RepoPath::new("docker-compose.yml").unwrap(),
    );
    edge(&run.linked, &compose, &smtp, EdgeKind::Defines);

    // A template-literal i18n key links ambiguously to every candidate.
    let page = symbol(
        "storefront-web",
        "src/pages/orders/index.tsx#OrderHistoryPage",
    );
    for status in ["pending", "paid", "shipped", "cancelled"] {
        let key = NodeId::contract(ContractKind::I18nKey, &format!("orders.status.{status}"));
        let e = edge(&run.linked, &page, &key, EdgeKind::References);
        assert_eq!(e.resolution, Resolution::Ambiguous);
        assert_eq!(e.evidence, EvidenceType::Heuristic);
    }
    let tr = NodeId::file(
        &name("mobile-app"),
        &RepoPath::new("lib/l10n/app_tr.arb").unwrap(),
    );
    assert_eq!(graph.node(&tr).and_then(|n| n.attr("locale")), Some("tr"));

    // A topic chosen at run time stays visible as an unresolved use.
    let placeholder = NodeId::contract(ContractKind::Topic, "{}");
    let dynamic = edge(
        &run.linked,
        &symbol(
            "billing-api",
            "src/events/event-publisher.ts#EventPublisher.publish",
        ),
        &placeholder,
        EdgeKind::Produces,
    );
    assert_eq!(dynamic.resolution, Resolution::Unresolved);
    assert!(
        graph
            .node(&placeholder)
            .unwrap()
            .is_unresolved_placeholder()
    );
}

/// True observations about the fixture that are not planted issues:
/// `(code, subject or project/path, why it is expected)`.
const ALLOWED: &[(&str, &str, &str)] = &[
    (
        "graph.endpoint_without_client",
        "contract:endpoint:GET /v1/payments/{}",
        "ledger-service serves it; no indexed project calls it",
    ),
    (
        "graph.endpoint_without_client",
        "contract:endpoint:POST /v1/refunds",
        "manual refunds come from support tooling outside the workspace",
    ),
    (
        "graph.env_undeclared",
        "contract:env_name:BILLING_API_URL",
        "a Flutter --dart-define build variable, not deployment config",
    ),
    (
        "graph.env_undeclared",
        "contract:env_name:NEXT_PUBLIC_BILLING_API_URL",
        "a Next.js build-time variable; infra/ does not deploy the website",
    ),
    (
        "graph.env_undeclared",
        "contract:env_name:NEXT_PUBLIC_ORDERS_API_URL",
        "a Next.js build-time variable; infra/ does not deploy the website",
    ),
    (
        "graph.env_undeclared",
        "contract:env_name:EXPORT_SECRET_ACCESS_KEY",
        "the export job's secret is declared in no Compose / Kubernetes file",
    ),
    (
        "graph.table_never_read",
        "contract:table:customers",
        "owned by the identity team, outside the workspace",
    ),
    (
        "graph.table_never_read",
        "contract:table:notification_log",
        "notification-worker's core code does not read it",
    ),
    (
        "graph.topic_without_consumer",
        "contract:topic:subscription.resumed",
        "billing-api publishes it; no project consumes it",
    ),
    (
        "link.unresolved_reference",
        "billing-api/src/payments/ledger.client.ts",
        "post(path) helper: the path is a parameter",
    ),
    (
        "link.unresolved_reference",
        "billing-api/src/events/event-publisher.ts",
        "producer.send({ topic: type }): the topic is a parameter",
    ),
    (
        "link.unresolved_reference",
        "notification-worker/src/config.rs",
        "required(name) / optional(name) env helpers",
    ),
    (
        "link.unresolved_reference",
        "orders-service/cmd/orders/main.go",
        "getenv(name, fallback) env helper",
    ),
    (
        "link.unresolved_reference",
        "orders-service/internal/events/consumer.go",
        "newReader(brokers, topic): the topic is a parameter",
    ),
    (
        "link.unresolved_reference",
        "storefront-web/src/api/client.ts",
        "request(baseUrl, path) wrapper: the URL is assembled at run time",
    ),
];

/// Codes that generated noise files may trigger: noise calls endpoints,
/// uses i18n keys and defines topics and tables that intentionally do not
/// exist elsewhere.
const NOISE_CODES: &[&str] = &[
    "graph.i18n_key_undefined",
    "graph.table_never_read",
    "graph.topic_without_consumer",
    "graph.topic_without_producer",
    "graph.endpoint_without_client",
    "link.endpoint_without_provider",
    "link.unresolved_reference",
];

fn primary(finding: &Finding) -> String {
    finding
        .locations
        .first()
        .map(|l| format!("{}/{}", l.project, l.path))
        .unwrap_or_default()
}

/// The planted issue a finding reports, if any.
fn planted_issue(finding: &Finding) -> Option<&'static str> {
    let subject = finding.subject.as_ref().map(NodeId::as_str).unwrap_or("");
    let project = finding.project.as_ref().map(Name::as_str).unwrap_or("");
    match (finding.code.as_str(), subject, project) {
        (
            "link.migration_entity_mismatch" | "graph.contract_drift",
            "contract:table:subscriptions",
            "ledger-service",
        ) if primary(finding) == "ledger-service/ledger/db/models.py" => {
            Some("schema-drift-cancel-reason")
        }
        (
            "link.endpoint_undocumented",
            "contract:endpoint:POST /v1/subscriptions/{}/resume",
            "billing-api",
        ) => Some("contract-drift-resume-endpoint"),
        _ => None,
    }
}

fn allowed(finding: &Finding) -> Option<&'static str> {
    let subject = finding.subject.as_ref().map(NodeId::as_str).unwrap_or("");
    let primary = primary(finding);
    ALLOWED
        .iter()
        .find(|(code, target, _)| {
            *code == finding.code && (*target == subject || *target == primary)
        })
        .map(|(_, _, why)| *why)
}

fn only_in_noise(run: &Run, finding: &Finding) -> bool {
    !finding.locations.is_empty()
        && finding
            .locations
            .iter()
            .all(|l| !is_core(&run.fixture, l.project.as_str(), l.path.as_str()))
}

#[test]
fn check_reports_the_planted_issues_and_nothing_spurious() {
    let run = run();
    let mut found_planted: BTreeMap<&str, Vec<&Finding>> = BTreeMap::new();
    let mut found_allowed: BTreeSet<(&str, &str)> = BTreeSet::new();
    let mut unexpected = Vec::new();
    for finding in &run.findings {
        if let Some(issue) = planted_issue(finding) {
            found_planted.entry(issue).or_default().push(finding);
        } else if let Some(why) = allowed(finding) {
            found_allowed.insert((finding.code.as_str(), why));
        } else if only_in_noise(run, finding) && NOISE_CODES.contains(&finding.code.as_str()) {
            // Generated noise refers to contracts that do not exist.
        } else {
            unexpected.push(format!(
                "{} {} @ {}",
                finding.code,
                finding.message,
                primary(finding)
            ));
        }
    }
    assert!(
        unexpected.is_empty(),
        "unexpected findings:\n{}",
        unexpected.join("\n")
    );

    // Both checkable planted issues are reported, with their evidence.
    let drift = found_planted
        .get("schema-drift-cancel-reason")
        .expect("schema drift not reported");
    let mismatch = drift
        .iter()
        .find(|f| f.code == "link.migration_entity_mismatch")
        .expect("migration/entity mismatch not reported");
    assert_eq!(mismatch.severity.as_str(), "error");
    assert!(
        mismatch
            .message
            .contains("`cancel_feedback`, `cancel_reason`"),
        "{}",
        mismatch.message
    );
    assert!(
        mismatch
            .locations
            .iter()
            .any(|l| l.path.as_str() == "migrations/0009_add_cancel_reason_to_subscriptions.sql"),
        "{mismatch:?}"
    );
    assert!(drift.iter().any(|f| f.code == "graph.contract_drift"));
    // billing-api's entity was updated: no finding for it.
    assert!(
        !run
            .findings
            .iter()
            .any(|f| primary(f).starts_with("billing-api/src/subscriptions/subscription.entity.ts"))
    );

    let resume = found_planted
        .get("contract-drift-resume-endpoint")
        .expect("undocumented resume endpoint not reported");
    let resume = resume.first().unwrap();
    assert_eq!(
        primary(resume),
        "billing-api/src/subscriptions/subscriptions.controller.ts"
    );
    assert!(
        resume
            .locations
            .iter()
            .any(|l| l.project.as_str() == "contracts"
                && l.path.as_str() == "openapi/billing-api.yaml"),
        "{resume:?}"
    );

    // Every allow-list entry is still observed (the list does not rot).
    let expected_allowed: BTreeSet<(&str, &str)> =
        ALLOWED.iter().map(|(code, _, why)| (*code, *why)).collect();
    assert_eq!(found_allowed, expected_allowed);

    // The planted issues of the fixture: the two above are reported by
    // `check`; the secret-file and hard-coded key issues are covered by
    // `secrets_are_never_read_or_emitted`.
    let ids: BTreeSet<&str> = planted_issues().iter().map(|p| p.id).collect();
    for id in found_planted.keys() {
        assert!(ids.contains(id), "{id}");
    }
}

fn outputs_text(run: &Run) -> String {
    let mut text = format!("{:?}\n{:?}\n", run.projects, run.findings);
    text.push_str(&format!("{:?}\n", run.linked));
    text.push_str(&sarif(run, "test").to_string());
    for delta in run
        .linked
        .deltas(
            &run.projects
                .iter()
                .map(|p| (p.project.clone(), 7))
                .collect(),
            None,
        )
        .unwrap()
    {
        text.push_str(&format!("{delta:?}\n"));
    }
    text
}

#[test]
fn secrets_are_never_read_or_emitted() {
    let run = run();
    // The committed .env is excluded by path before reading.
    let infra = run
        .projects
        .iter()
        .find(|p| p.project.as_str() == "infra")
        .unwrap();
    assert!(
        infra
            .skipped
            .iter()
            .any(|s| s.path.as_str() == ".env" && s.reason.starts_with("excluded")),
        "{:?}",
        infra.skipped
    );
    assert!(!run.read.get("infra").unwrap().contains(".env"));

    // Neither planted secret value appears in any output.
    let text = outputs_text(run);
    let canaries = run.fixture.canaries();
    assert_eq!(canaries.len(), 2);
    for canary in &canaries {
        assert!(!canary.is_empty());
        assert!(
            !text.contains(canary.as_str()),
            "a planted secret leaked into the output"
        );
    }
    // Env declarations carry names only: no value from Compose or
    // Kubernetes appears in any extraction.
    let extractions = format!("{:?}", run.projects);
    for value in [
        "no-reply@example.com",
        "kafka.platform.svc",
        "psp-sandbox.example.com",
        "http://ledger-service:8000",
    ] {
        assert!(
            !extractions.contains(value),
            "env value `{value}` was extracted"
        );
    }
    let names: BTreeSet<&str> = infra
        .extractions
        .iter()
        .filter(|e| e.kind == ContractKind::EnvName)
        .map(|e| e.key.as_str())
        .collect();
    assert!(names.contains("SMTP_PASSWORD") && names.contains("PSP_API_KEY"));
}

#[test]
fn sarif_output_is_valid_and_fingerprinted() {
    let run = run();
    let sarif = sarif(run, "0.0.0");
    assert_eq!(sarif["version"], "2.1.0");
    let tool = &sarif["runs"][0]["tool"]["driver"];
    let rules = tool["rules"].as_array().unwrap();
    let ids: Vec<&str> = rules.iter().map(|r| r["id"].as_str().unwrap()).collect();
    assert_eq!(ids, CHECK_RULES.iter().map(|r| r.code).collect::<Vec<_>>());
    let results = sarif["runs"][0]["results"].as_array().unwrap();
    assert_eq!(results.len(), run.findings.len());
    let mut fingerprints = BTreeSet::new();
    for (result, finding) in results.iter().zip(&run.findings) {
        let index = result["ruleIndex"].as_u64().unwrap() as usize;
        assert_eq!(rules[index]["id"], result["ruleId"]);
        let location = &result["locations"][0]["physicalLocation"];
        assert!(
            !location["artifactLocation"]["uri"]
                .as_str()
                .unwrap()
                .is_empty()
        );
        assert!(location["artifactLocation"].get("uriBaseId").is_none());
        let primary = finding.locations.first().unwrap();
        assert_eq!(
            location["artifactLocation"]["uri"],
            format!("file:///fixture/{}/{}", primary.project, primary.path)
        );
        let related = result["relatedLocations"]
            .as_array()
            .map(Vec::as_slice)
            .unwrap_or_default();
        assert_eq!(related.len(), finding.locations.len().saturating_sub(1));
        for (related, source) in related.iter().zip(finding.locations.iter().skip(1)) {
            let artifact = &related["physicalLocation"]["artifactLocation"];
            assert!(artifact.get("uriBaseId").is_none());
            assert_eq!(
                artifact["uri"],
                format!("file:///fixture/{}/{}", source.project, source.path)
            );
        }
        assert!(location["region"]["startLine"].as_u64().unwrap() >= 1);
        let fingerprint = result["partialFingerprints"][FINGERPRINT_KEY]
            .as_str()
            .unwrap();
        assert_eq!(fingerprint.len(), 64);
        fingerprints.insert(fingerprint.to_owned());
        assert!(["note", "warning", "error"].contains(&result["level"].as_str().unwrap()));
    }
    assert_eq!(
        fingerprints.len(),
        results.len(),
        "fingerprints must be unique"
    );
    let bases = sarif["runs"][0]["originalUriBaseIds"].as_object().unwrap();
    assert!(bases.contains_key("ledger-service"));
    assert_eq!(
        bases["ledger-service"]["uri"],
        "file:///fixture/ledger-service/"
    );
}

#[test]
fn results_are_deterministic() {
    let first = run();
    let second = execute();
    assert_eq!(first.projects, second.projects);
    assert_eq!(first.linked, second.linked);
    assert_eq!(first.findings, second.findings);
    assert_eq!(sarif(first, "x"), sarif(&second, "x"));
}

#[test]
fn deltas_apply_to_a_graph_and_respect_existing_nodes() {
    let run = run();
    let generations: BTreeMap<Name, u64> = run
        .projects
        .iter()
        .map(|p| (p.project.clone(), 3))
        .collect();
    let mut graph = knowell_graph::CodeGraph::new();
    for delta in run.linked.deltas(&generations, None).unwrap() {
        graph.apply(delta).unwrap();
    }
    assert!(graph.node_count() > 100);
    // A second link of the same view, at a newer generation, only adds
    // what the graph lacks and applies cleanly.
    let newer: BTreeMap<Name, u64> = generations.keys().map(|p| (p.clone(), 4)).collect();
    for delta in run.linked.deltas(&newer, Some(&graph)).unwrap() {
        assert!(delta.added_nodes.iter().all(|n| n.project.is_none()));
        graph.apply(delta).unwrap();
    }
    let missing = BTreeMap::new();
    assert!(run.linked.deltas(&missing, None).is_err());
}

#[test]
#[ignore = "developer aid: prints core-file extractions and all findings"]
fn print_fixture_results() {
    let run = run();
    for project in &run.projects {
        println!("##### {} packs={:?}", project.project, project.packs);
        for skipped in &project.skipped {
            println!("  skipped {} ({})", skipped.path, skipped.reason);
        }
        for e in &project.extractions {
            if is_core(&run.fixture, project.project.as_str(), e.path.as_str()) {
                println!("  {}:{} {}", e.path, e.range.start(), e.describe());
            }
        }
    }
    println!("##### findings");
    for f in &run.findings {
        println!(
            "  {} {} [{}] {} @ {}",
            if only_in_noise(run, f) {
                "noise"
            } else {
                "CORE "
            },
            f.code,
            f.severity.as_str(),
            f.message,
            primary(f)
        );
    }
}
