//! Integration tests for knowell-index against a real PostgreSQL with
//! pgvector and real git repositories generated by `knowell-eval`.
//!
//! Set `KNOWELL_TEST_DATABASE_URL` to an admin connection URL (see the
//! knowell-store README); without it every test prints one skip line and
//! passes (a failure under `KNOWELL_TEST_STRICT=1`). Embeddings use a counting wrapper around `FakeEmbedder`; no real
//! provider is ever contacted.

// Test helpers outside `#[test]` functions may panic and print.
#![allow(
    clippy::unwrap_used,
    clippy::expect_used,
    clippy::panic,
    clippy::indexing_slicing,
    clippy::print_stderr
)]

mod common;

mod durability;
mod failures;
mod incremental;
mod initial;
mod inputs;
mod limits;
mod linking;
mod overlay;
mod references;
mod scoping;
mod searchable;
mod watching;
