//! Generated-file detection: generator banners, lockfiles and well-known
//! generated-file names.
//!
//! Generated code is still indexed, but it is flagged so that search can
//! link it to its source and avoid duplicate results (ARCHITECTURE §7).

use knowell_core::RepoPath;

use crate::text::prefix;

/// How much of the file head is scanned for banners. Generators put their
/// banner at the top; Go requires it before the package clause.
const HEADER_BYTES: usize = 8 * 1024;
const HEADER_LINES: usize = 40;

/// Banners matched case-sensitively (conventions with fixed spelling).
const EXACT_MARKERS: &[&str] = &["@generated", "DO NOT EDIT", "<auto-generated"];

/// Banners matched case-insensitively.
const LOWER_MARKERS: &[&str] = &[
    "code generated by",
    "this file was generated",
    "this file is generated",
    "this file was automatically generated",
    "this file is automatically generated",
    "this file has been generated",
    "automatically generated by",
    "auto-generated by",
    "autogenerated by",
    "generated by the protocol buffer compiler",
    "generated by protoc",
    "protoc-gen-",
    "openapi generator",
    "openapi-generator",
    "swagger-codegen",
    "this code was generated by a tool",
];

/// File names that are always generated (lockfiles).
const LOCKFILES: &[&str] = &[
    "cargo.lock",
    "package-lock.json",
    "npm-shrinkwrap.json",
    "yarn.lock",
    "pnpm-lock.yaml",
    "bun.lock",
    "deno.lock",
    "poetry.lock",
    "pipfile.lock",
    "uv.lock",
    "composer.lock",
    "gemfile.lock",
    "go.sum",
    "podfile.lock",
    "pubspec.lock",
    "package.resolved",
    "packages.lock.json",
    "flake.lock",
    "mix.lock",
    "gradle.lockfile",
];

/// Suffixes of generated outputs (protobuf, Dart builders, designers,
/// minified bundles, source maps). Compared case-insensitively.
const SUFFIXES: &[&str] = &[
    ".min.js",
    ".min.mjs",
    ".min.css",
    ".js.map",
    ".css.map",
    ".pb.go",
    ".pb.gw.go",
    "_pb2.py",
    "_pb2.pyi",
    "_pb2_grpc.py",
    ".pb.cc",
    ".pb.h",
    "_pb.js",
    "_pb.d.ts",
    "_grpc_pb.js",
    ".pb.swift",
    ".grpc.swift",
    ".g.dart",
    ".freezed.dart",
    ".designer.cs",
    ".g.cs",
    ".generated.cs",
];

/// Whether the file is generated, judged by its name and the banner in its
/// first lines.
pub(crate) fn is_generated(path: &RepoPath, text: &str) -> bool {
    let name = path.file_name().to_ascii_lowercase();
    if LOCKFILES.contains(&name.as_str()) || SUFFIXES.iter().any(|s| name.ends_with(s)) {
        return true;
    }
    let head = prefix(text, HEADER_BYTES);
    let head = match head.match_indices('\n').nth(HEADER_LINES) {
        Some((i, _)) => head.get(..i).unwrap_or(head),
        None => head,
    };
    if EXACT_MARKERS.iter().any(|m| head.contains(m)) {
        return true;
    }
    let lower = head.to_lowercase();
    LOWER_MARKERS.iter().any(|m| lower.contains(m))
}

#[cfg(test)]
mod tests {
    use super::*;

    fn generated(path: &str, text: &str) -> bool {
        is_generated(&RepoPath::new(path).unwrap(), text)
    }

    #[test]
    fn banners() {
        assert!(generated(
            "x.go",
            "// Code generated by protoc-gen-go. DO NOT EDIT.\npackage x\n"
        ));
        assert!(generated("x.rs", "// @generated by build.rs\nfn a() {}\n"));
        assert!(generated(
            "x.cs",
            "// <auto-generated>\n//   This code was generated by a tool.\n"
        ));
        assert!(generated(
            "client.ts",
            "/**\n * Billing API\n * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).\n */\n"
        ));
        assert!(generated(
            "x_pb2.py",
            "# Generated by the protocol buffer compiler.  DO NOT EDIT!\n"
        ));
        assert!(!generated("x.rs", "fn main() {}\n"));
        assert!(!generated(
            "README.md",
            "# Tool\nIt writes files that say do not edit.\n"
        ));
    }

    #[test]
    fn banner_after_the_header_is_ignored() {
        let mut text = "fn a() {}\n".repeat(100);
        text.push_str("// DO NOT EDIT\n");
        assert!(!generated("x.rs", &text));
    }

    #[test]
    fn names() {
        assert!(generated("Cargo.lock", ""));
        assert!(generated("web/package-lock.json", "{}"));
        assert!(generated("dist/app.min.js", "var a=1"));
        assert!(generated("api/billing.pb.go", "package billing"));
        assert!(generated("lib/model.g.dart", "part of 'model.dart';"));
        assert!(generated("Forms/Main.Designer.cs", "partial class Main {}"));
        assert!(!generated("src/main.js", "var a = 1;"));
    }
}
