//! Integration tests for knowell-engine against a real PostgreSQL with
//! pgvector and git repositories generated by `knowell-eval`.
//!
//! Set `KNOWELL_TEST_DATABASE_URL` to an admin connection URL (see the
//! knowell-store README); without it every test prints one skip line and
//! passes, unless `KNOWELL_TEST_STRICT=1` turns the skip into a failure. Embeddings use `FakeEmbedder`; no real provider is contacted.

// Test helpers outside `#[test]` functions may panic and print.
#![allow(
    clippy::unwrap_used,
    clippy::expect_used,
    clippy::panic,
    clippy::indexing_slicing,
    clippy::print_stderr
)]

mod common;

mod checkpoint_receipts;
mod context_scope;
mod end_to_end;
mod hub_identity;
mod inspect_coverage;
mod memory_freshness;
mod memory_visibility;
mod profile_switch;
mod profiles;
mod relations_privacy;
mod rest_permissions;
mod source_context;
mod source_fetch;
mod usage_durability;
