//! Integration tests for knowell-engine against a real PostgreSQL with
//! pgvector and git repositories generated by `knowell-eval`.
//!
//! Set `KNOWELL_TEST_DATABASE_URL` to an admin connection URL (see the
//! knowell-store README); without it every test prints one skip line and
//! passes. Embeddings use `FakeEmbedder`; no real provider is contacted.

// Test helpers outside `#[test]` functions may panic and print.
#![allow(
    clippy::unwrap_used,
    clippy::expect_used,
    clippy::panic,
    clippy::indexing_slicing,
    clippy::print_stderr
)]

mod common;

mod end_to_end;
