//! The rule packs bundled with the crate (the repository's `packs/`
//! directory), embedded at build time. Fixtures under `packs/*/tests/` are
//! not embedded; the pack tests read them from disk. The test
//! `embedded_file_list_is_current` fails when this list and the directory
//! differ; regenerate it with
//! `cargo test -p knowell-link --test packs regenerate_builtin -- --ignored`.

use std::collections::BTreeMap;

/// `(pack, path inside the pack, content)`.
pub(crate) const FILES: &[(&str, &str, &str)] = &[
    (
        "api-specs",
        "pack.toml",
        include_str!("../../../../packs/api-specs/pack.toml"),
    ),
    (
        "aspnet",
        "pack.toml",
        include_str!("../../../../packs/aspnet/pack.toml"),
    ),
    (
        "aspnet",
        "csharp/class_route.scm",
        include_str!("../../../../packs/aspnet/csharp/class_route.scm"),
    ),
    (
        "aspnet",
        "csharp/http_attribute.scm",
        include_str!("../../../../packs/aspnet/csharp/http_attribute.scm"),
    ),
    (
        "aspnet",
        "csharp/minimal_api.scm",
        include_str!("../../../../packs/aspnet/csharp/minimal_api.scm"),
    ),
    (
        "constants",
        "pack.toml",
        include_str!("../../../../packs/constants/pack.toml"),
    ),
    (
        "constants",
        "csharp/const.scm",
        include_str!("../../../../packs/constants/csharp/const.scm"),
    ),
    (
        "constants",
        "dart/const.scm",
        include_str!("../../../../packs/constants/dart/const.scm"),
    ),
    (
        "constants",
        "go/const.scm",
        include_str!("../../../../packs/constants/go/const.scm"),
    ),
    (
        "constants",
        "java/const.scm",
        include_str!("../../../../packs/constants/java/const.scm"),
    ),
    (
        "constants",
        "kotlin/const.scm",
        include_str!("../../../../packs/constants/kotlin/const.scm"),
    ),
    (
        "constants",
        "python/const.scm",
        include_str!("../../../../packs/constants/python/const.scm"),
    ),
    (
        "constants",
        "rust/const.scm",
        include_str!("../../../../packs/constants/rust/const.scm"),
    ),
    (
        "constants",
        "typescript/const.scm",
        include_str!("../../../../packs/constants/typescript/const.scm"),
    ),
    (
        "dart-http-client",
        "pack.toml",
        include_str!("../../../../packs/dart-http-client/pack.toml"),
    ),
    (
        "dart-http-client",
        "dart/dio.scm",
        include_str!("../../../../packs/dart-http-client/dart/dio.scm"),
    ),
    (
        "dart-http-client",
        "dart/http_package.scm",
        include_str!("../../../../packs/dart-http-client/dart/http_package.scm"),
    ),
    (
        "env",
        "pack.toml",
        include_str!("../../../../packs/env/pack.toml"),
    ),
    (
        "env",
        "csharp/getenv.scm",
        include_str!("../../../../packs/env/csharp/getenv.scm"),
    ),
    (
        "env",
        "dart/from_environment.scm",
        include_str!("../../../../packs/env/dart/from_environment.scm"),
    ),
    (
        "env",
        "go/getenv.scm",
        include_str!("../../../../packs/env/go/getenv.scm"),
    ),
    (
        "env",
        "go/helper.scm",
        include_str!("../../../../packs/env/go/helper.scm"),
    ),
    (
        "env",
        "java/getenv.scm",
        include_str!("../../../../packs/env/java/getenv.scm"),
    ),
    (
        "env",
        "kotlin/getenv.scm",
        include_str!("../../../../packs/env/kotlin/getenv.scm"),
    ),
    (
        "env",
        "python/environ.scm",
        include_str!("../../../../packs/env/python/environ.scm"),
    ),
    (
        "env",
        "python/settings.scm",
        include_str!("../../../../packs/env/python/settings.scm"),
    ),
    (
        "env",
        "rust/env_var.scm",
        include_str!("../../../../packs/env/rust/env_var.scm"),
    ),
    (
        "env",
        "rust/helper.scm",
        include_str!("../../../../packs/env/rust/helper.scm"),
    ),
    (
        "env",
        "typescript/process_env.scm",
        include_str!("../../../../packs/env/typescript/process_env.scm"),
    ),
    (
        "env",
        "typescript/process_env_index.scm",
        include_str!("../../../../packs/env/typescript/process_env_index.scm"),
    ),
    (
        "express",
        "pack.toml",
        include_str!("../../../../packs/express/pack.toml"),
    ),
    (
        "express",
        "typescript/route_object.scm",
        include_str!("../../../../packs/express/typescript/route_object.scm"),
    ),
    (
        "express",
        "typescript/routes.scm",
        include_str!("../../../../packs/express/typescript/routes.scm"),
    ),
    (
        "go-http",
        "pack.toml",
        include_str!("../../../../packs/go-http/pack.toml"),
    ),
    (
        "go-http",
        "go/group.scm",
        include_str!("../../../../packs/go-http/go/group.scm"),
    ),
    (
        "go-http",
        "go/router.scm",
        include_str!("../../../../packs/go-http/go/router.scm"),
    ),
    (
        "go-http",
        "go/servemux.scm",
        include_str!("../../../../packs/go-http/go/servemux.scm"),
    ),
    (
        "go-http-client",
        "pack.toml",
        include_str!("../../../../packs/go-http-client/pack.toml"),
    ),
    (
        "go-http-client",
        "go/new_request.scm",
        include_str!("../../../../packs/go-http-client/go/new_request.scm"),
    ),
    (
        "gorm",
        "pack.toml",
        include_str!("../../../../packs/gorm/pack.toml"),
    ),
    (
        "gorm",
        "go/field.scm",
        include_str!("../../../../packs/gorm/go/field.scm"),
    ),
    (
        "gorm",
        "go/model.scm",
        include_str!("../../../../packs/gorm/go/model.scm"),
    ),
    (
        "gorm",
        "go/table_name.scm",
        include_str!("../../../../packs/gorm/go/table_name.scm"),
    ),
    (
        "grpc",
        "pack.toml",
        include_str!("../../../../packs/grpc/pack.toml"),
    ),
    (
        "grpc",
        "go/client_binding.scm",
        include_str!("../../../../packs/grpc/go/client_binding.scm"),
    ),
    (
        "grpc",
        "go/client_call.scm",
        include_str!("../../../../packs/grpc/go/client_call.scm"),
    ),
    (
        "grpc",
        "go/server_binding.scm",
        include_str!("../../../../packs/grpc/go/server_binding.scm"),
    ),
    (
        "grpc",
        "go/server_method.scm",
        include_str!("../../../../packs/grpc/go/server_method.scm"),
    ),
    (
        "grpc",
        "python/servicer.scm",
        include_str!("../../../../packs/grpc/python/servicer.scm"),
    ),
    (
        "grpc",
        "python/stub_binding.scm",
        include_str!("../../../../packs/grpc/python/stub_binding.scm"),
    ),
    (
        "grpc",
        "python/stub_call.scm",
        include_str!("../../../../packs/grpc/python/stub_call.scm"),
    ),
    (
        "grpc",
        "typescript/add_service.scm",
        include_str!("../../../../packs/grpc/typescript/add_service.scm"),
    ),
    (
        "grpc",
        "typescript/client_binding.scm",
        include_str!("../../../../packs/grpc/typescript/client_binding.scm"),
    ),
    (
        "grpc",
        "typescript/client_call.scm",
        include_str!("../../../../packs/grpc/typescript/client_call.scm"),
    ),
    (
        "i18n",
        "pack.toml",
        include_str!("../../../../packs/i18n/pack.toml"),
    ),
    (
        "i18n",
        "dart/l10n_binding.scm",
        include_str!("../../../../packs/i18n/dart/l10n_binding.scm"),
    ),
    (
        "i18n",
        "dart/l10n_direct.scm",
        include_str!("../../../../packs/i18n/dart/l10n_direct.scm"),
    ),
    (
        "i18n",
        "dart/l10n_variable.scm",
        include_str!("../../../../packs/i18n/dart/l10n_variable.scm"),
    ),
    (
        "i18n",
        "javascript/trans.scm",
        include_str!("../../../../packs/i18n/javascript/trans.scm"),
    ),
    (
        "i18n",
        "tsx/trans.scm",
        include_str!("../../../../packs/i18n/tsx/trans.scm"),
    ),
    (
        "i18n",
        "typescript/t_call.scm",
        include_str!("../../../../packs/i18n/typescript/t_call.scm"),
    ),
    (
        "infra",
        "pack.toml",
        include_str!("../../../../packs/infra/pack.toml"),
    ),
    (
        "js-http-client",
        "pack.toml",
        include_str!("../../../../packs/js-http-client/pack.toml"),
    ),
    (
        "js-http-client",
        "typescript/client_config.scm",
        include_str!("../../../../packs/js-http-client/typescript/client_config.scm"),
    ),
    (
        "js-http-client",
        "typescript/client_method.scm",
        include_str!("../../../../packs/js-http-client/typescript/client_method.scm"),
    ),
    (
        "js-http-client",
        "typescript/fetch.scm",
        include_str!("../../../../packs/js-http-client/typescript/fetch.scm"),
    ),
    (
        "js-http-client",
        "typescript/wrapper.scm",
        include_str!("../../../../packs/js-http-client/typescript/wrapper.scm"),
    ),
    (
        "kafka",
        "pack.toml",
        include_str!("../../../../packs/kafka/pack.toml"),
    ),
    (
        "kafka",
        "go/consumer_call.scm",
        include_str!("../../../../packs/kafka/go/consumer_call.scm"),
    ),
    (
        "kafka",
        "go/consumer_struct.scm",
        include_str!("../../../../packs/kafka/go/consumer_struct.scm"),
    ),
    (
        "kafka",
        "go/producer_struct.scm",
        include_str!("../../../../packs/kafka/go/producer_struct.scm"),
    ),
    (
        "kafka",
        "java/listener.scm",
        include_str!("../../../../packs/kafka/java/listener.scm"),
    ),
    (
        "kafka",
        "java/send.scm",
        include_str!("../../../../packs/kafka/java/send.scm"),
    ),
    (
        "kafka",
        "python/consumer.scm",
        include_str!("../../../../packs/kafka/python/consumer.scm"),
    ),
    (
        "kafka",
        "python/send.scm",
        include_str!("../../../../packs/kafka/python/send.scm"),
    ),
    (
        "kafka",
        "rust/record.scm",
        include_str!("../../../../packs/kafka/rust/record.scm"),
    ),
    (
        "kafka",
        "rust/subscribe.scm",
        include_str!("../../../../packs/kafka/rust/subscribe.scm"),
    ),
    (
        "kafka",
        "rust/topic_match.scm",
        include_str!("../../../../packs/kafka/rust/topic_match.scm"),
    ),
    (
        "kafka",
        "typescript/publish_wrapper.scm",
        include_str!("../../../../packs/kafka/typescript/publish_wrapper.scm"),
    ),
    (
        "kafka",
        "typescript/send.scm",
        include_str!("../../../../packs/kafka/typescript/send.scm"),
    ),
    (
        "kafka",
        "typescript/subscribe.scm",
        include_str!("../../../../packs/kafka/typescript/subscribe.scm"),
    ),
    (
        "nats",
        "pack.toml",
        include_str!("../../../../packs/nats/pack.toml"),
    ),
    (
        "nats",
        "go/publish.scm",
        include_str!("../../../../packs/nats/go/publish.scm"),
    ),
    (
        "nats",
        "go/subscribe.scm",
        include_str!("../../../../packs/nats/go/subscribe.scm"),
    ),
    (
        "nats",
        "python/publish.scm",
        include_str!("../../../../packs/nats/python/publish.scm"),
    ),
    (
        "nats",
        "python/subscribe.scm",
        include_str!("../../../../packs/nats/python/subscribe.scm"),
    ),
    (
        "nats",
        "typescript/publish.scm",
        include_str!("../../../../packs/nats/typescript/publish.scm"),
    ),
    (
        "nats",
        "typescript/subscribe.scm",
        include_str!("../../../../packs/nats/typescript/subscribe.scm"),
    ),
    (
        "nestjs",
        "pack.toml",
        include_str!("../../../../packs/nestjs/pack.toml"),
    ),
    (
        "nestjs",
        "typescript/messages.scm",
        include_str!("../../../../packs/nestjs/typescript/messages.scm"),
    ),
    (
        "nestjs",
        "typescript/routes.scm",
        include_str!("../../../../packs/nestjs/typescript/routes.scm"),
    ),
    (
        "nextjs",
        "pack.toml",
        include_str!("../../../../packs/nextjs/pack.toml"),
    ),
    (
        "nextjs",
        "typescript/app_route.scm",
        include_str!("../../../../packs/nextjs/typescript/app_route.scm"),
    ),
    (
        "nextjs",
        "typescript/pages_api.scm",
        include_str!("../../../../packs/nextjs/typescript/pages_api.scm"),
    ),
    (
        "prisma",
        "pack.toml",
        include_str!("../../../../packs/prisma/pack.toml"),
    ),
    (
        "python-http-client",
        "pack.toml",
        include_str!("../../../../packs/python-http-client/pack.toml"),
    ),
    (
        "python-http-client",
        "python/client_call.scm",
        include_str!("../../../../packs/python-http-client/python/client_call.scm"),
    ),
    (
        "python-orm",
        "pack.toml",
        include_str!("../../../../packs/python-orm/pack.toml"),
    ),
    (
        "python-orm",
        "python/django_field.scm",
        include_str!("../../../../packs/python-orm/python/django_field.scm"),
    ),
    (
        "python-orm",
        "python/django_foreign_key.scm",
        include_str!("../../../../packs/python-orm/python/django_foreign_key.scm"),
    ),
    (
        "python-orm",
        "python/django_meta.scm",
        include_str!("../../../../packs/python-orm/python/django_meta.scm"),
    ),
    (
        "python-orm",
        "python/sqlalchemy_column.scm",
        include_str!("../../../../packs/python-orm/python/sqlalchemy_column.scm"),
    ),
    (
        "python-orm",
        "python/sqlalchemy_model.scm",
        include_str!("../../../../packs/python-orm/python/sqlalchemy_model.scm"),
    ),
    (
        "python-web",
        "pack.toml",
        include_str!("../../../../packs/python-web/pack.toml"),
    ),
    (
        "python-web",
        "python/route.scm",
        include_str!("../../../../packs/python-web/python/route.scm"),
    ),
    (
        "python-web",
        "python/router_prefix.scm",
        include_str!("../../../../packs/python-web/python/router_prefix.scm"),
    ),
    (
        "python-web",
        "python/routes.scm",
        include_str!("../../../../packs/python-web/python/routes.scm"),
    ),
    (
        "rabbitmq",
        "pack.toml",
        include_str!("../../../../packs/rabbitmq/pack.toml"),
    ),
    (
        "rabbitmq",
        "go/consume.scm",
        include_str!("../../../../packs/rabbitmq/go/consume.scm"),
    ),
    (
        "rabbitmq",
        "go/publish.scm",
        include_str!("../../../../packs/rabbitmq/go/publish.scm"),
    ),
    (
        "rabbitmq",
        "java/consume.scm",
        include_str!("../../../../packs/rabbitmq/java/consume.scm"),
    ),
    (
        "rabbitmq",
        "java/publish.scm",
        include_str!("../../../../packs/rabbitmq/java/publish.scm"),
    ),
    (
        "rabbitmq",
        "python/consume.scm",
        include_str!("../../../../packs/rabbitmq/python/consume.scm"),
    ),
    (
        "rabbitmq",
        "python/publish.scm",
        include_str!("../../../../packs/rabbitmq/python/publish.scm"),
    ),
    (
        "rabbitmq",
        "typescript/consume.scm",
        include_str!("../../../../packs/rabbitmq/typescript/consume.scm"),
    ),
    (
        "rabbitmq",
        "typescript/publish.scm",
        include_str!("../../../../packs/rabbitmq/typescript/publish.scm"),
    ),
    (
        "redis-pubsub",
        "pack.toml",
        include_str!("../../../../packs/redis-pubsub/pack.toml"),
    ),
    (
        "redis-pubsub",
        "go/publish.scm",
        include_str!("../../../../packs/redis-pubsub/go/publish.scm"),
    ),
    (
        "redis-pubsub",
        "go/subscribe.scm",
        include_str!("../../../../packs/redis-pubsub/go/subscribe.scm"),
    ),
    (
        "redis-pubsub",
        "python/publish.scm",
        include_str!("../../../../packs/redis-pubsub/python/publish.scm"),
    ),
    (
        "redis-pubsub",
        "python/subscribe.scm",
        include_str!("../../../../packs/redis-pubsub/python/subscribe.scm"),
    ),
    (
        "redis-pubsub",
        "typescript/publish.scm",
        include_str!("../../../../packs/redis-pubsub/typescript/publish.scm"),
    ),
    (
        "redis-pubsub",
        "typescript/subscribe.scm",
        include_str!("../../../../packs/redis-pubsub/typescript/subscribe.scm"),
    ),
    (
        "retrofit",
        "pack.toml",
        include_str!("../../../../packs/retrofit/pack.toml"),
    ),
    (
        "retrofit",
        "java/service.scm",
        include_str!("../../../../packs/retrofit/java/service.scm"),
    ),
    (
        "retrofit",
        "kotlin/service.scm",
        include_str!("../../../../packs/retrofit/kotlin/service.scm"),
    ),
    (
        "spring",
        "pack.toml",
        include_str!("../../../../packs/spring/pack.toml"),
    ),
    (
        "spring",
        "java/class_prefix.scm",
        include_str!("../../../../packs/spring/java/class_prefix.scm"),
    ),
    (
        "spring",
        "java/mapping.scm",
        include_str!("../../../../packs/spring/java/mapping.scm"),
    ),
    (
        "spring",
        "java/request_mapping.scm",
        include_str!("../../../../packs/spring/java/request_mapping.scm"),
    ),
    (
        "spring",
        "kotlin/class_prefix.scm",
        include_str!("../../../../packs/spring/kotlin/class_prefix.scm"),
    ),
    (
        "spring",
        "kotlin/mapping.scm",
        include_str!("../../../../packs/spring/kotlin/mapping.scm"),
    ),
    (
        "sql-in-code",
        "pack.toml",
        include_str!("../../../../packs/sql-in-code/pack.toml"),
    ),
    (
        "sql-in-code",
        "csharp/sql_string.scm",
        include_str!("../../../../packs/sql-in-code/csharp/sql_string.scm"),
    ),
    (
        "sql-in-code",
        "go/sql_string.scm",
        include_str!("../../../../packs/sql-in-code/go/sql_string.scm"),
    ),
    (
        "sql-in-code",
        "java/sql_string.scm",
        include_str!("../../../../packs/sql-in-code/java/sql_string.scm"),
    ),
    (
        "sql-in-code",
        "kotlin/sql_string.scm",
        include_str!("../../../../packs/sql-in-code/kotlin/sql_string.scm"),
    ),
    (
        "sql-in-code",
        "python/sql_string.scm",
        include_str!("../../../../packs/sql-in-code/python/sql_string.scm"),
    ),
    (
        "sql-in-code",
        "rust/sql_string.scm",
        include_str!("../../../../packs/sql-in-code/rust/sql_string.scm"),
    ),
    (
        "sql-in-code",
        "typescript/sql_string.scm",
        include_str!("../../../../packs/sql-in-code/typescript/sql_string.scm"),
    ),
    (
        "sql-migrations",
        "pack.toml",
        include_str!("../../../../packs/sql-migrations/pack.toml"),
    ),
    (
        "swift-urlsession",
        "pack.toml",
        include_str!("../../../../packs/swift-urlsession/pack.toml"),
    ),
    (
        "swift-urlsession",
        "swift/http_method.scm",
        include_str!("../../../../packs/swift-urlsession/swift/http_method.scm"),
    ),
    (
        "swift-urlsession",
        "swift/url_string.scm",
        include_str!("../../../../packs/swift-urlsession/swift/url_string.scm"),
    ),
    (
        "typeorm",
        "pack.toml",
        include_str!("../../../../packs/typeorm/pack.toml"),
    ),
    (
        "typeorm",
        "typescript/column.scm",
        include_str!("../../../../packs/typeorm/typescript/column.scm"),
    ),
    (
        "typeorm",
        "typescript/entity.scm",
        include_str!("../../../../packs/typeorm/typescript/entity.scm"),
    ),
];

/// Files of every bundled pack, grouped by pack name.
pub(crate) fn pack_files() -> BTreeMap<&'static str, BTreeMap<String, String>> {
    let mut packs: BTreeMap<&'static str, BTreeMap<String, String>> = BTreeMap::new();
    for (pack, path, content) in FILES {
        packs
            .entry(*pack)
            .or_default()
            .insert((*path).to_owned(), (*content).to_owned());
    }
    packs
}
