//! Repository write-back: rendering accepted knowledge into Markdown
//! documents, and detecting documentation drift.

use std::collections::BTreeSet;

use knowell_core::{Name, RepoPath};
use schemars::JsonSchema;
use serde::{Deserialize, Serialize};

use crate::error::KnowledgeError;
use crate::guard::check_no_secrets;
use crate::model::{Evidence, KnowledgeRecord, RecordState, Scope};

const BEGIN_PREFIX: &str = "<!-- knowell:begin";
const END_MARKER: &str = "<!-- knowell:end -->";

/// Renders the accepted records of exactly `scope` as a managed section.
///
/// The section is delimited by `<!-- knowell:begin id=<id> scope=<scope> -->`
/// and `<!-- knowell:end -->` so [`replace_section`] can update it in place
/// without touching the rest of the document. Output is deterministic:
/// records are ordered by subject then id, there are no timestamps, and the
/// same input always renders the same text. Only accepted records of the
/// scope are rendered; stale, proposed, rejected and superseded records
/// never appear. Each record lists its sources as links.
///
/// Marker-like text inside record bodies is neutralised so a body can never
/// close or forge a section. The rendered text is secret-scanned as a last
/// line of defence.
pub fn render_section(
    id: &Name,
    scope: &Scope,
    heading: &str,
    records: &[KnowledgeRecord],
) -> Result<String, KnowledgeError> {
    let mut chosen: Vec<&KnowledgeRecord> = records
        .iter()
        .filter(|r| r.state == RecordState::Accepted && &r.scope == scope)
        .collect();
    chosen.sort_by(|a, b| (&a.subject, a.id).cmp(&(&b.subject, b.id)));

    let heading = heading.trim();
    if heading.is_empty() || heading.contains(['\n', '\r']) {
        return Err(KnowledgeError::InvalidField {
            field: "heading",
            reason: "must be a single non-empty line",
        });
    }
    let mut out = String::new();
    out.push_str(&format!(
        "{BEGIN_PREFIX} id={id} scope={} -->\n",
        scope.key()
    ));
    out.push_str("<!-- Generated by Knowell from accepted records. Edit the records, not this section. -->\n\n");
    out.push_str(&format!("{heading}\n"));
    if chosen.is_empty() {
        out.push_str("\n_No accepted records._\n");
    }
    for r in chosen {
        out.push_str(&format!("\n### {}\n\n", r.title));
        out.push_str(&format!(
            "_subject {} - {} - record `{}` v{}_\n\n",
            r.subject, r.kind, r.id, r.version
        ));
        out.push_str(&neutralise_markers(r.body.trim()));
        out.push('\n');
        if !r.evidence.is_empty() {
            out.push_str("\nSources:\n");
            for ev in &r.evidence {
                out.push_str(&format!("- {}\n", source_link(ev)));
            }
        }
    }
    out.push_str(END_MARKER);
    out.push('\n');
    check_no_secrets("rendered section", &out)?;
    Ok(out)
}

fn neutralise_markers(text: &str) -> String {
    text.replace("<!-- knowell:", "<!-- knowell-escaped:")
}

fn source_link(ev: &Evidence) -> String {
    let (start, end) = (ev.range.start(), ev.range.end());
    let label = format!("{}:{}:{}-{}", ev.project, ev.path, start, end)
        .replace('[', "\\[")
        .replace(']', "\\]");
    let target: String = ev
        .path
        .as_str()
        .chars()
        .flat_map(|c| match c {
            ' ' => "%20".chars().collect::<Vec<_>>(),
            '(' => "%28".chars().collect(),
            ')' => "%29".chars().collect(),
            other => vec![other],
        })
        .collect();
    format!(
        "[{label}]({target}#L{start}-L{end}) @{}",
        ev.commit.as_str().get(..7).unwrap_or(ev.commit.as_str())
    )
}

/// Inserts or replaces the managed section `id` in `document`.
///
/// `section` must come from [`render_section`] for the same `id`. If the
/// document already holds a section with this id, exactly the lines from its
/// begin marker to its end marker are replaced; everything else, including
/// line endings, is preserved. Otherwise the section is appended after a
/// blank line. Re-applying the same section is a no-op, so write-back is
/// idempotent.
///
/// Malformed markers (an unterminated section, a stray end marker, nested
/// sections, or two sections with the same id) are an error: the document is
/// never guessed at.
pub fn replace_section(document: &str, id: &Name, section: &str) -> Result<String, KnowledgeError> {
    let crlf = document.contains("\r\n");
    let section = if crlf {
        section.replace('\n', "\r\n")
    } else {
        section.to_string()
    };

    let mut found: Option<(usize, usize)> = None; // byte range [start, end) of the managed block
    let mut open: Option<(usize, bool, u32)> = None; // (start offset, is target, line)
    let mut offset = 0usize;
    let mut line_no = 0u32;
    for segment in document.split_inclusive('\n') {
        line_no = line_no.saturating_add(1);
        let trimmed = segment.trim();
        let end_offset = offset + segment.len();
        if trimmed.starts_with(BEGIN_PREFIX) {
            if open.is_some() {
                return Err(KnowledgeError::MalformedMarkers {
                    line: line_no,
                    reason: "a section begins inside another section",
                });
            }
            open = Some((
                offset,
                section_id(trimmed).is_some_and(|s| s == id.as_str()),
                line_no,
            ));
        } else if trimmed == END_MARKER {
            match open.take() {
                None => {
                    return Err(KnowledgeError::MalformedMarkers {
                        line: line_no,
                        reason: "end marker without a begin marker",
                    });
                }
                Some((start, true, _)) => {
                    if found.is_some() {
                        return Err(KnowledgeError::MalformedMarkers {
                            line: line_no,
                            reason: "the same section id appears twice",
                        });
                    }
                    found = Some((start, end_offset));
                }
                Some((_, false, _)) => {}
            }
        }
        offset = end_offset;
    }
    if let Some((_, _, line)) = open {
        return Err(KnowledgeError::MalformedMarkers {
            line,
            reason: "section is never closed",
        });
    }

    match found {
        Some((start, end)) => {
            let mut out = String::with_capacity(document.len() + section.len());
            out.push_str(document.get(..start).unwrap_or_default());
            // Keep the original line ending of the end marker line.
            let original = document.get(start..end).unwrap_or_default();
            let ends_with_newline = original.ends_with('\n');
            if ends_with_newline {
                out.push_str(&section);
            } else {
                out.push_str(section.trim_end_matches(['\r', '\n']));
            }
            out.push_str(document.get(end..).unwrap_or_default());
            Ok(out)
        }
        None => {
            let eol = if crlf { "\r\n" } else { "\n" };
            let mut out = document.to_string();
            if !out.is_empty() {
                if !out.ends_with('\n') {
                    out.push_str(eol);
                }
                out.push_str(eol);
            }
            out.push_str(&section);
            Ok(out)
        }
    }
}

fn section_id(begin_line: &str) -> Option<&str> {
    begin_line
        .split_whitespace()
        .find_map(|part| part.strip_prefix("id="))
}

/// A reference in a document that does not resolve.
#[derive(Debug, Clone, PartialEq, Eq, PartialOrd, Ord, Serialize, Deserialize, JsonSchema)]
pub struct DriftRef {
    /// The symbol or path as written (normalised: no `()`, no line suffix).
    pub name: String,
    /// 1-based line of its first occurrence.
    pub line: u32,
}

/// Result of [`doc_drift`].
#[derive(Debug, Clone, Default, PartialEq, Eq, Serialize, Deserialize, JsonSchema)]
pub struct DriftReport {
    /// Referenced symbols that are not in the known set.
    pub missing_symbols: Vec<DriftRef>,
    /// Referenced paths that are not in the known set.
    pub missing_paths: Vec<DriftRef>,
    /// How many distinct symbol references were checked.
    pub checked_symbols: usize,
    /// How many distinct path references were checked.
    pub checked_paths: usize,
}

impl DriftReport {
    /// Whether every checked reference resolves.
    pub fn is_clean(&self) -> bool {
        self.missing_symbols.is_empty() && self.missing_paths.is_empty()
    }
}

const PATH_EXTENSIONS: &[&str] = &[
    "rs", "ts", "tsx", "js", "jsx", "mjs", "py", "go", "java", "kt", "swift", "rb", "php", "cs",
    "c", "h", "cpp", "hpp", "md", "toml", "json", "yaml", "yml", "sql", "proto", "sh", "gradle",
    "xml", "html", "css",
];

#[derive(Debug, Clone, PartialEq, Eq, PartialOrd, Ord)]
enum RefKind {
    Symbol,
    Path,
}

/// Lists symbols and files a Markdown document names that no longer exist.
///
/// This is a **heuristic**, tuned to avoid false alarms:
///
/// * References are read from inline code spans and link targets; fenced
///   code blocks are skipped.
/// * A span with whitespace, a URL, a glob, or an absolute path is ignored.
/// * It is a *path* if it contains `/` or ends in a known source/config
///   extension (a trailing `:line` or `#Lline` is dropped). A trailing `/`
///   names a directory, which exists if any known path lies under it.
/// * It is a *symbol* if it is qualified (`a::b`, `a.b` with a symbol-like
///   segment), has `()`, contains `_`, or is camelCase/PascalCase with an
///   inner capital. Plain lowercase words and short dotted lowercase names
///   (such as `foo.txt`) are ignored.
/// * A symbol is known if it equals a known symbol or is a trailing
///   `::`/`.` qualified suffix of one (`charge` is not checked, but
///   `Gateway::charge` matches `payments::Gateway::charge`).
///
/// Results are sorted by name; each name carries its first line.
pub fn doc_drift(
    markdown: &str,
    known_symbols: &BTreeSet<String>,
    known_paths: &BTreeSet<RepoPath>,
) -> DriftReport {
    use std::collections::BTreeMap;
    let mut seen: BTreeMap<(RefKind, String), u32> = BTreeMap::new();
    let mut fenced: Option<char> = None;
    let mut line_no = 0u32;
    for line in markdown.lines() {
        line_no = line_no.saturating_add(1);
        let trimmed = line.trim_start();
        let fence = if trimmed.starts_with("```") {
            Some('`')
        } else if trimmed.starts_with("~~~") {
            Some('~')
        } else {
            None
        };
        if let Some(f) = fence {
            fenced = match fenced {
                None => Some(f),
                Some(open) if open == f => None,
                other => other,
            };
            continue;
        }
        if fenced.is_some() || trimmed.starts_with("<!--") {
            continue;
        }
        for span in code_spans(line) {
            if let Some((kind, name)) = classify_span(span) {
                seen.entry((kind, name)).or_insert(line_no);
            }
        }
        for target in link_targets(line) {
            if let Some(path) = classify_link_target(&target) {
                seen.entry((RefKind::Path, path)).or_insert(line_no);
            }
        }
    }

    let mut report = DriftReport::default();
    for ((kind, name), line) in seen {
        match kind {
            RefKind::Symbol => {
                report.checked_symbols += 1;
                if !symbol_known(&name, known_symbols) {
                    report.missing_symbols.push(DriftRef { name, line });
                }
            }
            RefKind::Path => {
                report.checked_paths += 1;
                if !path_known(&name, known_paths) {
                    report.missing_paths.push(DriftRef { name, line });
                }
            }
        }
    }
    report
}

fn symbol_known(name: &str, known: &BTreeSet<String>) -> bool {
    if known.contains(name) {
        return true;
    }
    known.iter().any(|k| {
        k.strip_suffix(name)
            .is_some_and(|prefix| prefix.ends_with("::") || prefix.ends_with('.'))
    })
}

fn path_known(name: &str, known: &BTreeSet<RepoPath>) -> bool {
    if let Some(dir) = name.strip_suffix('/') {
        let prefix = format!("{dir}/");
        return known.iter().any(|p| p.as_str().starts_with(&prefix));
    }
    match RepoPath::new(name) {
        Ok(p) => known.contains(&p),
        Err(_) => true, // not a repository path at all (e.g. "../x"); do not report
    }
}

/// Contents of inline code spans on one line (single or multiple backticks).
fn code_spans(line: &str) -> Vec<&str> {
    let bytes = line.as_bytes();
    let mut spans = Vec::new();
    let mut i = 0;
    while i < bytes.len() {
        if bytes.get(i) != Some(&b'`') {
            i += 1;
            continue;
        }
        let mut run = 0;
        while bytes.get(i + run) == Some(&b'`') {
            run += 1;
        }
        let start = i + run;
        // Find the next run of exactly `run` backticks.
        let mut j = start;
        let mut close = None;
        while j < bytes.len() {
            if bytes.get(j) == Some(&b'`') {
                let mut r = 0;
                while bytes.get(j + r) == Some(&b'`') {
                    r += 1;
                }
                if r == run {
                    close = Some(j);
                    break;
                }
                j += r;
            } else {
                j += 1;
            }
        }
        match close {
            Some(end) => {
                if let Some(span) = line.get(start..end) {
                    spans.push(span);
                }
                i = end + run;
            }
            None => i = start,
        }
    }
    spans
}

/// Targets of inline links `[text](target)` on one line.
fn link_targets(line: &str) -> Vec<String> {
    let mut out = Vec::new();
    let mut rest = line;
    while let Some(pos) = rest.find("](") {
        let after = rest.get(pos + 2..).unwrap_or_default();
        match after.find(')') {
            Some(end) => {
                if let Some(t) = after.get(..end) {
                    out.push(t.to_string());
                }
                rest = after.get(end + 1..).unwrap_or_default();
            }
            None => break,
        }
    }
    out
}

fn classify_link_target(raw: &str) -> Option<String> {
    let target = raw.split_whitespace().next()?;
    if target.starts_with('#') || target.contains("://") || target.starts_with("mailto:") {
        return None;
    }
    let target = target.split(['#', '?']).next()?;
    let decoded = target
        .replace("%20", " ")
        .replace("%28", "(")
        .replace("%29", ")");
    path_candidate(&decoded)
}

fn path_candidate(raw: &str) -> Option<String> {
    let mut s = raw.trim();
    s = s.strip_prefix("./").unwrap_or(s);
    // Drop a trailing `:line` or `:line-line`.
    if let Some((head, tail)) = s.rsplit_once(':')
        && !tail.is_empty()
        && tail.chars().all(|c| c.is_ascii_digit() || c == '-')
    {
        s = head;
    }
    if s.is_empty()
        || s.starts_with('/')
        || s.chars()
            .any(|c| c.is_whitespace() || "*?{}<>$|\\".contains(c))
    {
        return None;
    }
    if !s
        .chars()
        .all(|c| c.is_ascii_alphanumeric() || "._-/@+~ ()".contains(c))
    {
        return None;
    }
    let has_slash = s.contains('/');
    let ext_ok = s.rsplit_once('.').is_some_and(|(stem, ext)| {
        !stem.is_empty() && !stem.ends_with('/') && PATH_EXTENSIONS.contains(&ext)
    });
    if has_slash || ext_ok {
        Some(s.to_string())
    } else {
        None
    }
}

fn classify_span(span: &str) -> Option<(RefKind, String)> {
    let s = span.trim();
    if s.is_empty() || s.chars().any(char::is_whitespace) || s.contains("://") {
        return None;
    }
    if let Some(path) = path_candidate(s) {
        // `a.b` style names with a source extension are paths; qualified
        // symbols never contain `/`, and `::` marks a symbol.
        if !s.contains("::") {
            return Some((RefKind::Path, path));
        }
    }
    symbol_candidate(s).map(|n| (RefKind::Symbol, n))
}

fn is_ident(seg: &str) -> bool {
    let mut chars = seg.chars();
    chars
        .next()
        .is_some_and(|c| c.is_ascii_alphabetic() || c == '_' || c == '$')
        && chars.all(|c| c.is_ascii_alphanumeric() || c == '_' || c == '$')
}

fn symbol_candidate(s: &str) -> Option<String> {
    let (core, called) = match s.strip_suffix("()") {
        Some(c) => (c, true),
        None => (s, false),
    };
    if core.is_empty() {
        return None;
    }
    let segments: Vec<&str> = core.split("::").flat_map(|part| part.split('.')).collect();
    if segments.is_empty() || !segments.iter().all(|seg| is_ident(seg)) {
        return None;
    }
    let qualified_colons = core.contains("::");
    let dotted = core.contains('.');
    let has_underscore = core.contains('_');
    let inner_capital = core.chars().skip(1).any(|c| c.is_ascii_uppercase())
        && core.chars().any(|c| c.is_ascii_lowercase());
    if dotted && !qualified_colons && !called && !has_underscore && !inner_capital {
        // `foo.txt`, `foo.bar`: far more likely file names or prose than symbols.
        let last = segments.last().copied().unwrap_or_default();
        if last.len() <= 4
            && last
                .chars()
                .all(|c| c.is_ascii_lowercase() || c.is_ascii_digit())
        {
            return None;
        }
    }
    if qualified_colons || dotted || called || has_underscore || inner_capital {
        Some(core.to_string())
    } else {
        None
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::ids::Subject;
    use crate::model::RecordKind;
    use crate::policy::{AcceptancePolicy, Rights};
    use crate::testutil::*;

    fn accepted(n: u128, subject: &str, title: &str, body: &str) -> KnowledgeRecord {
        let mut new = new_record(RecordKind::Human, n);
        new.subject = Subject::new(subject).unwrap();
        new.title = title.to_string();
        new.body = body.to_string();
        KnowledgeRecord::write(
            new,
            human("a"),
            Rights::REVIEWER,
            &AcceptancePolicy::default(),
            ts(1),
        )
        .unwrap()
        .record
    }

    fn scope() -> Scope {
        project_scope("api")
    }

    fn sid() -> Name {
        name("agents")
    }

    fn render(records: &[KnowledgeRecord]) -> String {
        render_section(&sid(), &scope(), "## Project knowledge", records).unwrap()
    }

    #[test]
    fn renders_markers_order_and_sources() {
        let records = vec![
            accepted(2, "b.second", "Second", "Body two."),
            accepted(1, "a.first", "First", "Body one."),
        ];
        let text = render(&records);
        assert!(text.starts_with("<!-- knowell:begin id=agents scope=project:shop/api -->\n"));
        assert!(text.ends_with("<!-- knowell:end -->\n"));
        let first = text.find("### First").unwrap();
        let second = text.find("### Second").unwrap();
        assert!(first < second, "ordered by subject");
        assert!(text.contains("[api:src/pay.rs:10-20](src/pay.rs#L10-L20) @abc1234"));
        assert!(text.contains("record `00000000-0000-0000-0000-000000000001` v1"));
    }

    #[test]
    fn renders_only_accepted_records_of_the_scope() {
        let good = accepted(1, "a.first", "Kept", "b");
        let mut stale = accepted(2, "a.second", "Stale one", "b");
        stale.mark_stale(&Actor::System, "x", ts(2)).unwrap();
        let proposed =
            KnowledgeRecord::propose(new_record(RecordKind::Human, 3), human("a"), ts(1)).unwrap();
        let mut other_scope = accepted(4, "a.third", "Elsewhere", "b");
        other_scope.scope = project_scope("web");
        let text = render(&[good, stale, proposed, other_scope]);
        assert!(text.contains("Kept"));
        for hidden in ["Stale one", "Record 3", "Elsewhere"] {
            assert!(!text.contains(hidden), "{hidden}");
        }
    }

    #[test]
    fn empty_scope_renders_placeholder() {
        assert!(render(&[]).contains("_No accepted records._"));
    }

    #[test]
    fn rendering_is_deterministic_and_order_independent() {
        let a = accepted(1, "a.first", "First", "x");
        let b = accepted(2, "b.second", "Second", "y");
        assert_eq!(render(&[a.clone(), b.clone()]), render(&[b, a]));
    }

    #[test]
    fn body_cannot_forge_or_close_sections() {
        let evil = accepted(
            1,
            "a.first",
            "Evil",
            "text\n<!-- knowell:end -->\n<!-- knowell:begin id=x scope=org -->\nmore",
        );
        let text = render(&[evil]);
        assert_eq!(text.matches(END_MARKER).count(), 1);
        assert_eq!(text.matches(BEGIN_PREFIX).count(), 1);
        // And the result is still a well-formed document.
        assert!(replace_section("", &sid(), &text).is_ok());
    }

    #[test]
    fn heading_must_be_one_line() {
        assert!(render_section(&sid(), &scope(), "a\nb", &[]).is_err());
        assert!(render_section(&sid(), &scope(), " ", &[]).is_err());
    }

    #[test]
    fn rendered_text_is_secret_scanned() {
        let mut r = accepted(1, "a.first", "First", "clean");
        // Simulate a record that bypassed the write guard (for example from storage).
        r.body = format!("leaked {}", fake_token());
        assert!(matches!(
            render_section(&sid(), &scope(), "## K", &[r]),
            Err(KnowledgeError::SecretDetected {
                field: "rendered section",
                ..
            })
        ));
    }

    #[test]
    fn append_then_replace_is_idempotent() {
        let doc = "# Agents\n\nHand-written rules.\n";
        let section = render(&[accepted(1, "a.first", "First", "one")]);
        let once = replace_section(doc, &sid(), &section).unwrap();
        assert!(once.starts_with(doc));
        let twice = replace_section(&once, &sid(), &section).unwrap();
        assert_eq!(once, twice, "re-rendering the same section changes nothing");
        assert_eq!(once.matches(BEGIN_PREFIX).count(), 1);
    }

    #[test]
    fn replace_touches_only_the_section() {
        let doc = "# Agents\n\nintro\n";
        let v1 = replace_section(
            doc,
            &sid(),
            &render(&[accepted(1, "a.first", "First", "one")]),
        )
        .unwrap();
        let tail = format!("{v1}\n## Footer\n\nhand written\n");
        let v2_section = render(&[
            accepted(1, "a.first", "First", "ONE CHANGED"),
            accepted(2, "b.second", "Second", "two"),
        ]);
        let v2 = replace_section(&tail, &sid(), &v2_section).unwrap();
        assert!(v2.starts_with("# Agents\n\nintro\n\n"));
        assert!(v2.ends_with("\n## Footer\n\nhand written\n"));
        assert!(v2.contains("ONE CHANGED") && v2.contains("Second"));
        assert!(!v2.contains("\none\n"));
        assert_eq!(replace_section(&v2, &sid(), &v2_section).unwrap(), v2);
    }

    #[test]
    fn other_sections_are_left_alone() {
        let other = render_section(&name("adr"), &Scope::Organization, "## ADR", &[]).unwrap();
        let doc = replace_section("", &name("adr"), &other).unwrap();
        let mine = render(&[accepted(1, "a.first", "First", "one")]);
        let both = replace_section(&doc, &sid(), &mine).unwrap();
        assert!(both.contains("id=adr") && both.contains("id=agents"));
        let updated = replace_section(&both, &sid(), &render(&[])).unwrap();
        assert!(
            updated.contains(&other),
            "the other section is byte-identical"
        );
    }

    #[test]
    fn crlf_documents_stay_crlf() {
        let doc = "# Agents\r\n\r\nintro\r\n";
        let section = render(&[accepted(1, "a.first", "First", "one")]);
        let once = replace_section(doc, &sid(), &section).unwrap();
        assert!(!once.replace("\r\n", "").contains('\n'), "no bare LF");
        assert_eq!(replace_section(&once, &sid(), &section).unwrap(), once);
    }

    #[test]
    fn document_without_trailing_newline_is_handled() {
        let section = render(&[]);
        let out = replace_section("no newline at end", &sid(), &section).unwrap();
        assert!(out.starts_with("no newline at end\n\n<!-- knowell:begin"));
    }

    #[test]
    fn malformed_markers_are_errors() {
        let section = render(&[]);
        let unclosed = "<!-- knowell:begin id=agents scope=org -->\ntext\n";
        assert!(matches!(
            replace_section(unclosed, &sid(), &section),
            Err(KnowledgeError::MalformedMarkers { line: 1, .. })
        ));
        let stray = "text\n<!-- knowell:end -->\n";
        assert!(matches!(
            replace_section(stray, &sid(), &section),
            Err(KnowledgeError::MalformedMarkers { line: 2, .. })
        ));
        let nested = "<!-- knowell:begin id=a scope=org -->\n<!-- knowell:begin id=b scope=org -->\n<!-- knowell:end -->\n";
        assert!(matches!(
            replace_section(nested, &sid(), &section),
            Err(KnowledgeError::MalformedMarkers { line: 2, .. })
        ));
        let twice = format!("{section}{section}");
        assert!(matches!(
            replace_section(&twice, &sid(), &section),
            Err(KnowledgeError::MalformedMarkers { .. })
        ));
    }

    fn syms(items: &[&str]) -> BTreeSet<String> {
        items.iter().map(|s| s.to_string()).collect()
    }

    fn paths(items: &[&str]) -> BTreeSet<RepoPath> {
        items.iter().map(|s| RepoPath::new(*s).unwrap()).collect()
    }

    #[test]
    fn drift_finds_missing_symbols_and_paths_with_lines() {
        let md = "# Notes\n\nCall `PaymentService.charge()` from `src/pay/gateway.rs`.\nSee [the doc](docs/old.md) and `refund_order`.\n";
        let report = doc_drift(
            md,
            &syms(&["PaymentService.charge", "other"]),
            &paths(&["src/pay/gateway.rs"]),
        );
        assert_eq!(
            report.missing_symbols,
            vec![DriftRef {
                name: "refund_order".into(),
                line: 4
            }]
        );
        assert_eq!(
            report.missing_paths,
            vec![DriftRef {
                name: "docs/old.md".into(),
                line: 4
            }]
        );
        assert_eq!(report.checked_symbols, 2);
        assert_eq!(report.checked_paths, 2);
        assert!(!report.is_clean());
    }

    #[test]
    fn drift_clean_document() {
        let md = "Use `Gateway::charge` in `src/a.rs`.";
        let report = doc_drift(
            md,
            &syms(&["payments::Gateway::charge"]),
            &paths(&["src/a.rs"]),
        );
        assert!(report.is_clean(), "{report:?}");
    }

    #[test]
    fn drift_skips_fenced_code_and_comments() {
        let md =
            "```\n`gone_symbol` src/gone.rs\n```\n<!-- `also_gone` -->\n~~~\n`gone_two`\n~~~\n";
        assert!(doc_drift(md, &BTreeSet::new(), &BTreeSet::new()).is_clean());
        let report = doc_drift(
            "```\ncode\n```\n`after_fence`",
            &BTreeSet::new(),
            &BTreeSet::new(),
        );
        assert_eq!(
            report.missing_symbols.len(),
            1,
            "text after a closed fence is checked again"
        );
    }

    #[test]
    fn drift_ignores_prose_and_commands() {
        let md = "Run `cargo test -p x`, set `true`, `null`, `Config`, `v1.2`, `foo.txt`, `https://example.com/a`, `src/*.rs`, `/abs/path.rs`, `e.g.`.";
        let report = doc_drift(md, &BTreeSet::new(), &BTreeSet::new());
        assert!(report.is_clean(), "{report:?}");
        assert_eq!(report.checked_symbols + report.checked_paths, 0);
    }

    #[test]
    fn drift_handles_line_suffixes_dirs_and_encoded_links() {
        let md = "`src/a.rs:42` `src/a.rs:10-20` `crates/old/` `crates/new/` [x](src/my%20file.rs#L3) [y](#anchor) [z](https://x.y/z.rs)";
        let report = doc_drift(
            md,
            &BTreeSet::new(),
            &paths(&["src/a.rs", "crates/new/lib.rs", "src/my file.rs"]),
        );
        assert_eq!(
            report.missing_paths,
            vec![DriftRef {
                name: "crates/old/".into(),
                line: 1
            }]
        );
    }

    #[test]
    fn drift_reports_first_line_once_and_sorted() {
        let md = "`zeta_fn`\n`alpha_fn`\n`zeta_fn` again\n";
        let report = doc_drift(md, &BTreeSet::new(), &BTreeSet::new());
        assert_eq!(
            report.missing_symbols,
            vec![
                DriftRef {
                    name: "alpha_fn".into(),
                    line: 2
                },
                DriftRef {
                    name: "zeta_fn".into(),
                    line: 1
                }
            ]
        );
    }

    #[test]
    fn drift_recognises_camel_and_pascal_case() {
        let md = "`processPayment` and `PaymentService`.";
        let report = doc_drift(md, &syms(&["PaymentService"]), &BTreeSet::new());
        assert_eq!(
            report
                .missing_symbols
                .iter()
                .map(|r| r.name.as_str())
                .collect::<Vec<_>>(),
            vec!["processPayment"]
        );
    }

    #[test]
    fn drift_survives_hostile_input() {
        for md in [
            "`",
            "``",
            "```",
            "`a",
            "](",
            "[x](",
            "[x]((",
            "`\u{0}`",
            "\u{feff}`ö_ö`",
            &"`".repeat(1000),
            &"[a](b".repeat(100),
        ] {
            let _ = doc_drift(md, &BTreeSet::new(), &BTreeSet::new());
        }
    }

    #[test]
    fn rendered_section_has_no_drift_when_sources_exist() {
        let records = vec![accepted(1, "a.first", "First", "see `Gateway::charge`")];
        let md = render(&records);
        let report = doc_drift(&md, &syms(&["Gateway::charge"]), &paths(&["src/pay.rs"]));
        assert!(report.is_clean(), "{report:?}");
        let gone = doc_drift(&md, &syms(&["Gateway::charge"]), &BTreeSet::new());
        assert_eq!(gone.missing_paths.len(), 1);
    }

    use crate::model::Actor;
}
