//! Typed identifiers. Every id is a UUIDv7 generated by the database, so ids
//! sort by creation time.

use std::fmt;

use uuid::Uuid;

macro_rules! id_type {
    ($(#[$doc:meta])* $name:ident) => {
        $(#[$doc])*
        #[derive(
            Clone, Copy, PartialEq, Eq, Hash, PartialOrd, Ord, Debug,
            serde::Serialize, serde::Deserialize, sqlx::Type,
        )]
        #[sqlx(transparent)]
        #[serde(transparent)]
        pub struct $name(pub Uuid);

        impl $name {
            /// The underlying UUID.
            pub fn as_uuid(&self) -> Uuid {
                self.0
            }
        }

        impl fmt::Display for $name {
            fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
                fmt::Display::fmt(&self.0, f)
            }
        }

        impl From<Uuid> for $name {
            fn from(value: Uuid) -> Self {
                Self(value)
            }
        }
    };
}

id_type!(
    /// Identifies an organization (tenant).
    OrganizationId
);
id_type!(
    /// Identifies a workspace.
    WorkspaceId
);
id_type!(
    /// Identifies a source (git repository or directory).
    SourceId
);
id_type!(
    /// Identifies a project.
    ProjectId
);
id_type!(
    /// Identifies a view (one project following one track target).
    ViewId
);
id_type!(
    /// Identifies a view manifest.
    ManifestId
);
id_type!(
    /// Identifies a logical symbol.
    SymbolId
);
id_type!(
    /// Identifies a symbol occurrence.
    OccurrenceId
);
id_type!(
    /// Identifies a graph edge.
    EdgeId
);
id_type!(
    /// Identifies a contract participation record.
    ContractId
);
id_type!(
    /// Identifies an embedding profile.
    ProfileId
);
id_type!(
    /// Identifies an index generation (view generation x embedding profile).
    IndexGenerationId
);
id_type!(
    /// Identifies a job in the durable queue.
    JobId
);
id_type!(
    /// Identifies a knowledge (memory) record. Chosen by the caller (the
    /// knowledge domain generates record ids), not by the database.
    KnowledgeRecordId
);
id_type!(
    /// Identifies a task. Chosen by the caller, like [`KnowledgeRecordId`].
    TaskId
);
id_type!(
    /// Identifies a blue-green embedding profile switch.
    ProfileSwitchId
);
id_type!(
    /// Identifies a checkpoint receipt. Derived by the caller from who saved
    /// the checkpoint and their idempotency key, so a retry names the same id.
    CheckpointReceiptId
);
id_type!(
    /// Identifies a principal (user or service account); the same UUID as
    /// the knowell-auth `UserId` / `ServiceAccountId`.
    PrincipalId
);
id_type!(
    /// Identifies a grant (principal x role x scope).
    GrantId
);
id_type!(
    /// Identifies an API token record; the same UUID as the knowell-auth
    /// `TokenId`.
    ApiTokenId
);
id_type!(
    /// Identifies an audit log entry.
    AuditEntryId
);
